### PR TITLE
Adds the destVincenty algorithm

### PR DESCRIPTION
**Pull request by l8nite**
This change adds the destVincenty algorithm:
http://www.movable-type.co.uk/scripts/latlong-vincenty-direct.html

Updated the README.md to include new usage and examples of both synchronous and asynchronous operation.

I also slightly modified the existing function to:
- make callback optional
- check # of arguments on callback function, and if 3, unpack the result data into the arguments directly -- see the README for example

### CODE REVIEW

**Comment by l8nite** [comment]
Also, thanks for packaging this up :+1:

**Comment by TankofVines** [comment]
Awesome. Thanks for contributing.

**Comment by l8nite** [comment]
Sure thing! Can you push a new package to npm? :)

**Comment by TankofVines** [comment]
I just published to npm. Let me know if you see any issues.

**Pull request merged**
